// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: ouchibucket/item/v1/item.proto

package itemv1

import (
	v1 "github.com/akimoto-junya/ouchi-hub-backend/grpc/ouchibucket/content/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *InsertItemRequest) Reset() {
	*x = InsertItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ouchibucket_item_v1_item_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertItemRequest) ProtoMessage() {}

func (x *InsertItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ouchibucket_item_v1_item_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertItemRequest.ProtoReflect.Descriptor instead.
func (*InsertItemRequest) Descriptor() ([]byte, []int) {
	return file_ouchibucket_item_v1_item_proto_rawDescGZIP(), []int{0}
}

func (x *InsertItemRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type InsertItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InsertItemResponse) Reset() {
	*x = InsertItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ouchibucket_item_v1_item_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertItemResponse) ProtoMessage() {}

func (x *InsertItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ouchibucket_item_v1_item_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertItemResponse.ProtoReflect.Descriptor instead.
func (*InsertItemResponse) Descriptor() ([]byte, []int) {
	return file_ouchibucket_item_v1_item_proto_rawDescGZIP(), []int{1}
}

type GetDirectoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Depth  int32  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
}

func (x *GetDirectoryRequest) Reset() {
	*x = GetDirectoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ouchibucket_item_v1_item_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryRequest) ProtoMessage() {}

func (x *GetDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ouchibucket_item_v1_item_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryRequest.ProtoReflect.Descriptor instead.
func (*GetDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_ouchibucket_item_v1_item_proto_rawDescGZIP(), []int{2}
}

func (x *GetDirectoryRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetDirectoryRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type GetDirectoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Directory *Directory `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
}

func (x *GetDirectoryResponse) Reset() {
	*x = GetDirectoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ouchibucket_item_v1_item_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryResponse) ProtoMessage() {}

func (x *GetDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ouchibucket_item_v1_item_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryResponse.ProtoReflect.Descriptor instead.
func (*GetDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_ouchibucket_item_v1_item_proto_rawDescGZIP(), []int{3}
}

func (x *GetDirectoryResponse) GetDirectory() *Directory {
	if x != nil {
		return x.Directory
	}
	return nil
}

type MoveItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId        string `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	DestDirectoryId string `protobuf:"bytes,2,opt,name=dest_directory_id,json=destDirectoryId,proto3" json:"dest_directory_id,omitempty"`
}

func (x *MoveItemRequest) Reset() {
	*x = MoveItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ouchibucket_item_v1_item_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveItemRequest) ProtoMessage() {}

func (x *MoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ouchibucket_item_v1_item_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveItemRequest.ProtoReflect.Descriptor instead.
func (*MoveItemRequest) Descriptor() ([]byte, []int) {
	return file_ouchibucket_item_v1_item_proto_rawDescGZIP(), []int{4}
}

func (x *MoveItemRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *MoveItemRequest) GetDestDirectoryId() string {
	if x != nil {
		return x.DestDirectoryId
	}
	return ""
}

type MoveItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveItemResponse) Reset() {
	*x = MoveItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ouchibucket_item_v1_item_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveItemResponse) ProtoMessage() {}

func (x *MoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ouchibucket_item_v1_item_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveItemResponse.ProtoReflect.Descriptor instead.
func (*MoveItemResponse) Descriptor() ([]byte, []int) {
	return file_ouchibucket_item_v1_item_proto_rawDescGZIP(), []int{5}
}

type Directory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Directories []*Directory `protobuf:"bytes,3,rep,name=directories,proto3" json:"directories,omitempty"`
	Files       []*File      `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *Directory) Reset() {
	*x = Directory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ouchibucket_item_v1_item_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_ouchibucket_item_v1_item_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_ouchibucket_item_v1_item_proto_rawDescGZIP(), []int{6}
}

func (x *Directory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Directory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Directory) GetDirectories() []*Directory {
	if x != nil {
		return x.Directories
	}
	return nil
}

func (x *Directory) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FileType v1.FileType `protobuf:"varint,3,opt,name=file_type,json=fileType,proto3,enum=ouchibucket.content.v1.FileType" json:"file_type,omitempty"`
	Url      string      `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ouchibucket_item_v1_item_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_ouchibucket_item_v1_item_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_ouchibucket_item_v1_item_proto_rawDescGZIP(), []int{7}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetFileType() v1.FileType {
	if x != nil {
		return x.FileType
	}
	return v1.FileType(0)
}

func (x *File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Entity:
	//
	//	*Item_Directory
	//	*Item_File
	Entity isItem_Entity `protobuf_oneof:"entity"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ouchibucket_item_v1_item_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_ouchibucket_item_v1_item_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_ouchibucket_item_v1_item_proto_rawDescGZIP(), []int{8}
}

func (m *Item) GetEntity() isItem_Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (x *Item) GetDirectory() *Directory {
	if x, ok := x.GetEntity().(*Item_Directory); ok {
		return x.Directory
	}
	return nil
}

func (x *Item) GetFile() *File {
	if x, ok := x.GetEntity().(*Item_File); ok {
		return x.File
	}
	return nil
}

type isItem_Entity interface {
	isItem_Entity()
}

type Item_Directory struct {
	Directory *Directory `protobuf:"bytes,1,opt,name=directory,proto3,oneof"`
}

type Item_File struct {
	File *File `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*Item_Directory) isItem_Entity() {}

func (*Item_File) isItem_Entity() {}

var File_ouchibucket_item_v1_item_proto protoreflect.FileDescriptor

var file_ouchibucket_item_v1_item_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x69, 0x74,
	0x65, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x69, 0x74,
	0x65, 0x6d, 0x2e, 0x76, 0x31, 0x1a, 0x26, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a,
	0x11, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x69,
	0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x22, 0x14, 0x0a, 0x12, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x22, 0x54, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x75, 0x63, 0x68, 0x69,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x22, 0x5a, 0x0a, 0x0f, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x64, 0x65, 0x73, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22,
	0x12, 0x0a, 0x10, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x75, 0x63,
	0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0b, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x7b, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x81, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x3e,
	0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x69, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x48, 0x00, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x2f,
	0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f,
	0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x42,
	0x08, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x32, 0xb0, 0x02, 0x0a, 0x0b, 0x49, 0x74,
	0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x0a, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x26, 0x2e, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x27, 0x2e, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x69, 0x74,
	0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x28, 0x2e, 0x6f, 0x75, 0x63,
	0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x59, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x24, 0x2e,
	0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x69, 0x74, 0x65, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0xde, 0x01, 0x0a,
	0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x6b, 0x69, 0x6d, 0x6f, 0x74, 0x6f, 0x2d, 0x6a, 0x75, 0x6e, 0x79, 0x61, 0x2f,
	0x6f, 0x75, 0x63, 0x68, 0x69, 0x2d, 0x68, 0x75, 0x62, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x69, 0x74, 0x65, 0x6d, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x4f, 0x49, 0x58, 0xaa, 0x02, 0x13, 0x4f, 0x75, 0x63, 0x68, 0x69, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x13,
	0x4f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5c, 0x49, 0x74, 0x65, 0x6d,
	0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1f, 0x4f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x5c, 0x49, 0x74, 0x65, 0x6d, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x15, 0x4f, 0x75, 0x63, 0x68, 0x69, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x3a, 0x3a, 0x49, 0x74, 0x65, 0x6d, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ouchibucket_item_v1_item_proto_rawDescOnce sync.Once
	file_ouchibucket_item_v1_item_proto_rawDescData = file_ouchibucket_item_v1_item_proto_rawDesc
)

func file_ouchibucket_item_v1_item_proto_rawDescGZIP() []byte {
	file_ouchibucket_item_v1_item_proto_rawDescOnce.Do(func() {
		file_ouchibucket_item_v1_item_proto_rawDescData = protoimpl.X.CompressGZIP(file_ouchibucket_item_v1_item_proto_rawDescData)
	})
	return file_ouchibucket_item_v1_item_proto_rawDescData
}

var file_ouchibucket_item_v1_item_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ouchibucket_item_v1_item_proto_goTypes = []interface{}{
	(*InsertItemRequest)(nil),    // 0: ouchibucket.item.v1.InsertItemRequest
	(*InsertItemResponse)(nil),   // 1: ouchibucket.item.v1.InsertItemResponse
	(*GetDirectoryRequest)(nil),  // 2: ouchibucket.item.v1.GetDirectoryRequest
	(*GetDirectoryResponse)(nil), // 3: ouchibucket.item.v1.GetDirectoryResponse
	(*MoveItemRequest)(nil),      // 4: ouchibucket.item.v1.MoveItemRequest
	(*MoveItemResponse)(nil),     // 5: ouchibucket.item.v1.MoveItemResponse
	(*Directory)(nil),            // 6: ouchibucket.item.v1.Directory
	(*File)(nil),                 // 7: ouchibucket.item.v1.File
	(*Item)(nil),                 // 8: ouchibucket.item.v1.Item
	(v1.FileType)(0),             // 9: ouchibucket.content.v1.FileType
}
var file_ouchibucket_item_v1_item_proto_depIdxs = []int32{
	8,  // 0: ouchibucket.item.v1.InsertItemRequest.item:type_name -> ouchibucket.item.v1.Item
	6,  // 1: ouchibucket.item.v1.GetDirectoryResponse.directory:type_name -> ouchibucket.item.v1.Directory
	6,  // 2: ouchibucket.item.v1.Directory.directories:type_name -> ouchibucket.item.v1.Directory
	7,  // 3: ouchibucket.item.v1.Directory.files:type_name -> ouchibucket.item.v1.File
	9,  // 4: ouchibucket.item.v1.File.file_type:type_name -> ouchibucket.content.v1.FileType
	6,  // 5: ouchibucket.item.v1.Item.directory:type_name -> ouchibucket.item.v1.Directory
	7,  // 6: ouchibucket.item.v1.Item.file:type_name -> ouchibucket.item.v1.File
	0,  // 7: ouchibucket.item.v1.ItemService.InsertItem:input_type -> ouchibucket.item.v1.InsertItemRequest
	2,  // 8: ouchibucket.item.v1.ItemService.GetDirectory:input_type -> ouchibucket.item.v1.GetDirectoryRequest
	4,  // 9: ouchibucket.item.v1.ItemService.MoveItem:input_type -> ouchibucket.item.v1.MoveItemRequest
	1,  // 10: ouchibucket.item.v1.ItemService.InsertItem:output_type -> ouchibucket.item.v1.InsertItemResponse
	3,  // 11: ouchibucket.item.v1.ItemService.GetDirectory:output_type -> ouchibucket.item.v1.GetDirectoryResponse
	5,  // 12: ouchibucket.item.v1.ItemService.MoveItem:output_type -> ouchibucket.item.v1.MoveItemResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ouchibucket_item_v1_item_proto_init() }
func file_ouchibucket_item_v1_item_proto_init() {
	if File_ouchibucket_item_v1_item_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ouchibucket_item_v1_item_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ouchibucket_item_v1_item_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ouchibucket_item_v1_item_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirectoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ouchibucket_item_v1_item_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirectoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ouchibucket_item_v1_item_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ouchibucket_item_v1_item_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ouchibucket_item_v1_item_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Directory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ouchibucket_item_v1_item_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ouchibucket_item_v1_item_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ouchibucket_item_v1_item_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Item_Directory)(nil),
		(*Item_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ouchibucket_item_v1_item_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ouchibucket_item_v1_item_proto_goTypes,
		DependencyIndexes: file_ouchibucket_item_v1_item_proto_depIdxs,
		MessageInfos:      file_ouchibucket_item_v1_item_proto_msgTypes,
	}.Build()
	File_ouchibucket_item_v1_item_proto = out.File
	file_ouchibucket_item_v1_item_proto_rawDesc = nil
	file_ouchibucket_item_v1_item_proto_goTypes = nil
	file_ouchibucket_item_v1_item_proto_depIdxs = nil
}
