// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id)
VALUES (?)
`

func (q *Queries) CreateUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, createUser, id)
	return err
}
