// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users
  (id)
VALUES
  ($1)
`

func (q *Queries) CreateUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, createUser, id)
	return err
}
